<Project Sdk="MSTest.Sdk/4.0.2">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <DefineConstants Condition="'$(GITHUB_ACTIONS)' == 'true'">$(DefineConstants);CI</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="GraphQL.MicrosoftDI" Version="8.8.0" />
    <PackageReference Include="Shane32.GraphQL.DI" Version="8.*" />
    <PackageReference Include="GraphQL.SystemTextJson" Version="8.8.0" />
    <PackageReference Include="GraphQL.DataLoader" Version="8.8.0" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="Microsoft.VisualStudio.TestTools.UnitTesting.ParallelizeAttribute" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="GraphQL.Linq.EntityFrameworkCore10" />
    <Using Include="GraphQL.Types" />
    <Using Include="GraphQL" />
    <Using Include="Microsoft.Extensions.DependencyInjection" />
    <Using Include="TestDb" />
    <Using Include="TestDb.Models" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GraphQL.Linq.EntityFrameworkCore10\GraphQL.Linq.EntityFrameworkCore10.csproj" />
    <ProjectReference Include="..\ObjectApprover\ObjectApprover.csproj" />
    <ProjectReference Include="..\TestDb\TestDb.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="**\*.approved.*;**\*.received.*">
      <DependentUpon>$([System.String]::Copy('%(Filename)').Split('.')[0]).cs</DependentUpon>
    </None>
  </ItemGroup>

</Project>
