<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Description>Adds LinqToDB mapping for GraphQL.Linq</Description>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <!-- NU5104 ignores the warning when a prelease version is referenced from a released version -->
    <PackageReference Include="linq2db" Version="6.0.0-rc.3" NoWarn="NU5104" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GraphQL.Linq\GraphQL.Linq.csproj" />
  </ItemGroup>

</Project>
