<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="GraphQL.Server.Ui.GraphiQL" Version="8.*" />
    <PackageReference Include="Shane32.GraphQL.DI" Version="8.*" />
    <PackageReference Include="GraphQL.SystemTextJson" Version="8.8.0" />
    <PackageReference Include="GraphQL.DataLoader" Version="8.8.0" />
    <PackageReference Include="GraphQL.Server.Transports.AspNetCore" Version="8.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GraphQL.Linq.EntityFrameworkCore8\GraphQL.Linq.EntityFrameworkCore8.csproj" />
    <ProjectReference Include="..\TechMartDb.EfCore8\TechMartDb.EfCore8.csproj" />
    <ProjectReference Include="..\DbHelpers\DbHelpers.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Remove="Microsoft.Extensions.Hosting" />
    <Using Remove="System.Net.Http.Json" />
    <Using Include="GraphQL.Linq" />
    <Using Include="GraphQL.Linq.EntityFrameworkCore8" />
    <Using Include="TechMartDb.TechMartDbContext" Alias="TechMartDbContext" />
    <Using Include="TechMartDb.Models" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\TechMart.EfCore2\Graphs\*.cs" Link="Graphs\%(RecursiveDir)%(Filename)%(Extension)" />
    <Compile Include="..\TechMart.EfCore3\Program.cs" />
  </ItemGroup>

</Project>
