<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Description>Adds EF Core mapping for GraphQL.Linq</Description>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.36" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GraphQL.Linq\GraphQL.Linq.csproj" />
  </ItemGroup>

</Project>
